config/routes.rb
Wint::Application.routes.draw do
  ##================================================
  ##  Session
  ##================================================

  ##--  Session
  get  'login'          => 'sessions#new', as: :login
  post 'login'          => 'sessions#create'
  get  'logout'         => 'sessions#destroy', as: :logout
  get  'destroy_player' => 'sessions#destroy_player', as: :destroy_player

  ##================================================
  ##  Analysis
  ##================================================

  ##--  Analysis
  get 'analysis'                 => 'analysis#list', as: :analysis_list
  get 'analysis/:lid'            => 'analysis#league', as: :analysis_league
  get 'analysis/:lid/refresh'    => 'analysis#refresh', as: :analysis_refresh
  get 'analysis/:lid/strategies' => 'analysis#strategies', as: :analysis_strategies
  get 'analysis/:lid/player_ranking' => 'analysis#player_ranking', as: :analysis_player_ranking
  get 'analysis/:lid/strategy_ranking' => 'analysis#strategy_ranking', as: :analysis_strategy_ranking
  get 'analysis/:lid/code/:sid'  => 'analysis#code', as: :analysis_player_code
  get 'analysis/:lid/:pid'       => 'analysis#player', as: :analysis_player
  get 'analysis/:lid/:pid/:num'  => 'analysis#strategy', as: :analysis_strategy

  ##--  Download
  get 'downloads/:lid/best_strategies' => 'download#best_strategies', as: :download_best_strategies
  get 'downloads/:lid/all_strategies'  => 'download#all_strategies', as: :download_all_strategies
  get 'downloads/:lid/best_analysis'   => 'download#best_analysis', as: :download_best_analysis
  get 'downloads/:lid/all_analysis'    => 'download#all_analysis', as: :download_all_analysis

  ##================================================
  ##  Main
  ##================================================
  ##--  Main
  get   'main/select'                => 'mains#select', as: :main_select
  get   'main/set_player/:pid'       => 'mains#set_player', as: :main_set_player
  get   'main/ranking'               => 'mains#ranking', as: :main_ranking
  get   'main/mypage'                => 'mains#mypage', as: :main_mypage
  get   'main/mypage/strategy/:num'  => 'mains#strategy', as: :main_strategy
  get   'main/mypage/submit'         => 'submits#new', as: :submits_new
  post  'main/mypage/submit'         => 'submits#create'
  get   'main/edit_name'             => 'mains#edit_name', as: :main_edit_name
  patch 'main/edit_name'             => 'mains#update_name'
  get   'main/edit_password'         => 'mains#edit_password', as: :main_edit_password
  patch 'main/edit_password'         => 'mains#update_password'

  ##================================================
  ##  Admin
  ##================================================

  ##--  User
  get   'admin/users'                    => 'users#list', as: :users
  get   'admin/users/new'                => 'users#new', as: :users_new
  post  'admin/users/new'                => 'users#create'
  get   'admin/users/new_many'           => 'users#new_many', as: :users_new_many
  post  'admin/users/new_many'           => 'users#create_many'
  get   'admin/users/:uid/edit'          => 'users#edit', as: :users_edit
  patch 'admin/users/:uid/edit'          => 'users#update'
  get   'admin/users/:uid/edit_password' => 'users#edit_password', as: :users_edit_password
  patch 'admin/users/:uid/edit_password' => 'users#update_password', as: :users_update_password
  get   'admin/users/:uid/toggle'        => 'users#toggle', as: :users_toggle

  ##--  League
  get   'admin/leagues'                   => 'leagues#list', as: :leagues
  get   'admin/leagues/new'               => 'leagues#new', as: :leagues_new
  post  'admin/leagues/new'               => 'leagues#create'
  get   'admin/leagues/:lid/edit'         => 'leagues#edit', as: :leagues_edit
  patch 'admin/leagues/:lid/edit'         => 'leagues#update'
  get   'admin/leagues/:lid/toggle'       => 'leagues#toggle', as: :leagues_toggle
  get   'admin/leagues/:lid/toggle_analy' => 'leagues#toggle_analy', as: :leagues_toggle_analy

  ##--  Player
  get   'admin/players'             => 'players#list', as: :players
  get   'admin/players/select'      => 'players#select', as: :players_select
  get   'admin/players/new_many'    => 'players#new_many', as: :players_new_many
  post  'admin/players/new_many'    => 'players#create_many'
  get   'admin/players/new'         => 'players#new', as: :players_new
  post  'admin/players/new'         => 'players#create'
  get   'admin/players/:pid/edit'   => 'players#edit', as: :players_edit
  patch 'admin/players/:pid/edit'   => 'players#update'
  get   'admin/players/:pid/toggle' => 'players#toggle', as: :players_toggle
end

app/models/concerns/analysis/adlint/adlint_function.rb
class AdlintFunction
  attr_reader :name, :position, :text, :metrix, :assignment

  def initialize(name, position)
    @name = name
    @position = position
    @text = ''
    @metrix = {}
    @assignment = []
  end

  def add_metrix(type, value)
    @metrix[type] = value
  end

  def add_assignment(pos, to, from)
    @assignment << [pos, to, from]
  end

  def add_text(text)
    @text = text
  end

  def branch
    @metrix['FN_CSUB'] || 0
  end

  def statement
    @metrix['FN_STMT'] || 0
  end

  def condition
    @text.gsub(/&&/, 'and').gsub(/\|\|/, 'or')
         .scan(/\s(if|while|for|case|and|or)/).count
  end

  def abc_size
    a = @assignment.count
    b = branch
    c = condition
    Math.sqrt(a**2 + b**2 + c**2)
  end

  public_class_method

  def self.global
    new('global', 0)
  end
end

app/models/concerns/analysis/adlint_analysis.rb
class AdlintAnalysis
  def initialize(analysis_path)
    @path = analysis_path + '/adlint'
    @adlint_file_path = @path + '/adlint.c'
    @adlint_metrix_path = @path + '/output/adlint.c.met.csv'
  end

  def analyze_func_num
    functions.values.count
  end

  def analyze_abc_size
    value = functions.values.map(&:abc_size).inject(0) { |sum, v| sum + v**2 }
    Math.sqrt(value / analyze_func_num)
  end

  def analyze_statement
    functions.values.map(&:statement).inject(:+)
  end

  def functions
    return @functions if @functions

    @functions = { 'global' => AdlintFunction.global }
    file_data = File.read(@adlint_file_path).split(/\r\n|\n/)
    data = File.read(@adlint_metrix_path).split(/\r\n|\n/)

    data.each do |line|
      next unless line =~ /^(DEF|MET|ASN|INI)/
      e = CSV.parse(line).first
      if e.first == 'DEF' && e[4] == 'F'
        name = e[7]
        start_line = e[2].to_i - 1
        end_line = start_line + e[9].to_i
        @functions[name] = AdlintFunction.new(name, start_line)
        @functions[name].add_text(file_data[start_line...end_line].join("\n"))
      elsif line =~ /^MET,FN/
        name = e[2]
        @functions[name].add_metrix(e[1], e[7].to_i)
      elsif line =~ /^(ASN|INI)/
        pos = e[2].to_i
        name = function_name(@functions.values, pos)
        @functions[name].add_assignment(pos, e[4], e[5])
      end
    end
    @functions
  end

  private

  def function_name(functions, position)
    functions.reverse_each do |function|
      return function.name if function.position < position
    end
    'global'
  end

  public_class_method

  def self.create(analysis_path, content)
    path = analysis_path + '/adlint'
    Dir.mkdir(path)

    content.gsub!(/#include/, '// #include')
    File.write(path + '/adlint.c', content)
    Rake.sh "cd #{path} && adlintize -o output && cd #{path}/output && make verbose-all"

    new(analysis_path)
  end
end

app/models/concerns/analysis/code_analysis.rb
class CodeAnalysis
  def initialize(analysis_path)
    @path = analysis_path + '/code'
    @base_file_path = @path + '/comcut.c'
  end

  public_class_method

  def self.create(analysis_path, content)
    path = analysis_path + '/code'
    Dir.mkdir(path)

    content = content.split(/\r\n|\n/).delete_if { |line| line =~ /^#include/ }
    comcut_path = path + '/comcut.c'
    File.write(comcut_path, content.join("\n"))
    comcut_content = `gcc -E -P #{comcut_path}`.split(/\r\n|\n/)
    File.write(comcut_path, comcut_content.join("\n"))

    new(analysis_path)
  end
end

app/models/concerns/analysis/log_analysis.rb
class LogAnalysis
  def initialize(analysis_path)
    @path = analysis_path + '/log'
    @base_file_path = @path + '/Game.log'
  end

  public_class_method

  def self.create(analysis_path, content)
    path = analysis_path + '/log'
    Dir.mkdir(path)
    File.write(path + '/Game.log', content)
    new(analysis_path)
  end
end

app/models/concerns/analysis/result_analysis.rb
class ResultAnalysis
  def initialize(analysis_path)
    @path = analysis_path + '/result'
    @base_file_path = @path + '/Result.txt'
  end

  def result_table
    File.read(@base_file_path).split(/\r\n|\n/)
      .map { |line| line.gsub(/\||-|\+/, '').split }
      .delete_if { |line| line.empty? || line.first == '平均得点' }
  end

  def analyze_score
    File.read(@base_file_path).split.last.to_f
  end

  public_class_method

  def self.create(analysis_path, content)
    path = analysis_path + '/result'
    Dir.mkdir(path)
    File.write(path + '/Result.txt', content)
    new(analysis_path)
  end
end

app/controllers/analysis_controller.rb
class AnalysisController < ApplicationController
  include GraphGenerator

  def list
    @leagues = League.active
  end

  def league
    @league = League.includes(players: [:submits, :strategies]).find(params[:lid])
    @column_strategies_per_day = column_strategies_per_day(@league.id)
    @line_strategies_total = line_strategies_total(@league.id)
  end

  def player_ranking
    @league = League.includes(players: [{best: :strategy}, :strategies, :user, :submits]).find(params[:lid])
    @players = @league.players_ranking
    @players += @league.players.select {|p| !p.best}
  end

  def strategy_ranking
    @league = League.includes(players: [{best: :strategy}, :strategies, :user, :submits]).find(params[:lid])

    @strategies = @league.strategies.sort { |a, b| b.score <=> a.score }
  end

  def player
    @lid = params[:lid]
    @player = Player.find(params[:pid])
    @strategies = @player.strategies.number_by
    @line_score = line_score(@player.id)
  end

  def code
    @submit = Submit.where(id: params[:sid]).first
  end

  def strategy
    @lid = params[:lid]
    @strategy = Player.find(params[:pid]).strategies.where(number: params[:num]).first
    @scatter_abc_size = scatter_abc_size(@lid, @strategy.id)
    @result_table = @strategy.get_result_table
  end

  def strategies
    @lid = params[:lid]
    @scatter_abc_size = scatter_abc_size(params[:lid])
    @bar_submits = bar_submits(@lid)
  end

  def refresh
    @league = League.where(id: params[:lid]).first
    @league.players.each do |player|
      player.strategies.each { |strategy| strategy.analysis_update }
    end
    redirect_to analysis_league_path
  end
end

app/views/analysis/league.html.slim
.title
  .row
    .col-xs-5
      h2= "リーグ詳細 -#{@league.name}-"
    .col-xs-7
br
br

.col-md-3
  = render partial: 'shared/sidemenu', locals: { lid: @league.id, active: { league: 'active' } }

.col-md-9
  .row
    - participants = @league.participants
    - auditors = @league.auditors

    - participants_submits = participants_strategies = participants_max = 0
    - auditors_submits = auditors_strategies = auditors_max = 0

    table.table.table-base
      tr
        th
        th プレイヤ数
        th 提出数
        th 戦略数
        th 最多提出数
      tr
        - unless participants.blank?
          - participants_submits = participants.map { |p| p.submits.count }.inject(:+)
          - participants_strategies = participants.map { |p| p.strategies.count }.inject(:+)
          - participants_max = participants.map { |p| p.strategies.count }.max
        th 受講者
        td.right= participants.count
        td.right= participants_submits
        td.right= participants_strategies
        td.right= participants_max
      tr
        - unless auditors.blank?
          - auditors_submits = auditors.map { |p| p.submits.count }.inject(:+)
          - auditors_strategies = auditors.map { |p| p.strategies.count }.inject(:+)
          - auditors_max = auditors.map { |p| p.strategies.count }.max
        th 聴講者
        td.right= auditors.count
        td.right= auditors_submits
        td.right= auditors_strategies
        td.right= auditors_max
      tr
        th 合計
        td.right= @league.players.count
        td.right= participants_submits + auditors_submits
        td.right= participants_strategies + auditors_strategies
        td.right= participants_max > auditors_max ? participants_max : auditors_max

    .row
      .col-lg-6
        = high_chart('column_strategies_per_day', @column_strategies_per_day)
      .col-lg-6
        = high_chart('line_strategies_total', @line_strategies_total)

app/views/analysis/list.html.slim
.title
  .row
    .col-xs-5
      h2 分析ページ
    .col-xs-7
br
br

table.table.table-base
  thead
    tr
      th リーグ名
      th ルール
      th 開催期間
      th 戦略数
  tbody
    - @leagues.each do |league|
      tr
        td.center= link_to league.name, analysis_league_path(lid: league.id)
        td.center= league.format_rule
        td.center= format_time(league.start_at) + '～' + format_time(league.end_at)
        td.center= league.strategies.count

app/views/analysis/player.html.slim
.title
  .row
    .col-xs-5
      h2 プレイヤ詳細
    .col-xs-7
      br
      = link_to analysis_player_code_path(sid: @player.best.id), data: {remote: true}
        button.btn.btn-info
          | 最良戦略
br
br

.col-md-3
  = render partial: 'shared/sidemenu', locals: { lid: @lid, active: { player_ranking: 'active' } }
.col-md-9
  .row
    .col-md-4
      table.table-base
        tr
          th プレイヤ名
          td.center= @player.name
        tr
          th ユーザ名
          td.center= @player.user.name
        tr
          th 学籍番号
          td.center= @player.user.snum
        tr
          th 提出数
          td.center= @player.submits.count
        tr
          th 戦略数
          td.center= @player.strategies.count
    .col-md-8
      = high_chart('line_score', @line_score)

  table.table-base.datatable-desc
    thead
      tr
        th 戦略番号
        th コード
        th 得点
        th 提出日時
        th ABCサイズ
        th ステート数
        th 関数の定義数
    tbody
      - @strategies.each do |strategy|
        tr
          td.center= link_to "%03d" % strategy.number, analysis_strategy_path(num: strategy.number)
          td.center= link_to analysis_player_code_path(sid: strategy.submit.id), data: {remote: true}
            button.btn.btn-info コードを見る
          td.right= format_score(strategy.score)
          td.center= format_time(strategy.created_at)
          td.right= format_score(strategy.abc_size)
          td.right= strategy.statement
          td.right= strategy.func_num

app/views/analysis/player_ranking.html.slim
.title
  h2 プレイヤランキング
br
br

.col-md-3
  = render partial: 'shared/sidemenu', locals: { lid: @league.id, active: { player_ranking: 'active' } }

.col-md-9
  table.table-base.datatable50
    thead
      tr
        th 順位
        th 最良戦略
        th ユーザ名
        th 最終提出日
        th 得点
        th 最大ABCサイズ
        th ステート数
        th 関数の定義数
    tbody
      - @players.each.with_index(1) do |player, i|
        - if player.best
          - if player.auditor?
            | <tr class="warning">
          - else
            | <tr>
          td.center= i
          td.center= link_to "#{player.snum} (#{player.strategies.count})", analysis_player_path(pid: player.id)
          td.center= player.user.name
          td.center= format_time(player.strategies.max {|a, b| a.created_at <=> b.created_at}.created_at)
          td.right= format_score(player.best.strategy.score)
          td.right= format_score(player.best.strategy.abc_size)
          td.right= player.best.strategy.statement
          td.right= player.best.strategy.func_num
        - else
          tr.danger
            td.center= i
            td.center= player.user.snum
            td.center= player.user.name
            td.center 未提出
            td.right 0
            td.right 0
            td.right 0
            td.right 0

app/views/analysis/strategies.html.slim
.title
  .row
    .col-xs-5
      h2 戦略コード分析
    .col-xs-7
br
br

.col-md-3
  = render partial: 'shared/sidemenu', locals: { lid: @lid, active: { strategies: 'active' } }

.col-md-9
  .col-lg-12
    = high_chart('scatter_abc_size', @scatter_abc_size)
  .col-lg-12
    = high_chart('bar_submits', @bar_submits)

app/views/analysis/strategy.html.slim
.title
  .row
    .col-xs-5
      h2 戦略詳細
    .col-xs-7
      br
      = link_to analysis_player_code_path(sid: @strategy.submit.id), data: {remote: true}
        button.btn.btn-info
          | 戦略コード
br
br

.col-md-3
  = render partial: 'shared/sidemenu', locals: { lid: @lid, active: { player_ranking: 'active' } }
.col-md-9
  .row
    .col-lg-6
      table.table-base
        thead
          tr
            - @result_table.shift.each do |head|
              th= head
        tbody
          - @result_table.each do |line|
            tr
              td.name style="font-weight: bold;" = line.shift
              - line.each do |elem|
                td.num= elem
    .col-lg-6
      = high_chart('scatter_abc_size', @scatter_abc_size)
  .row
    table.table.table-base.datatable
      thead
        tr
          th 行番号
          th 関数名
          th ABCサイズ
          th 代入回数
          th 関数の呼出回数
          th 条件文の数
      tbody
        - @strategy.adlint_analysis.functions.values.each do |function|
          - abc_size = function.abc_size
          - klass = 'warning' if abc_size > 20
          - klass = 'danger' if abc_size > 30
          tr class="#{klass}"
            td.center= function.position
            td.center= function.name
            td.right= format_score(abc_size)
            td.right= function.assignment.count
            td.right= function.branch
            td.right= function.condition

app/views/analysis/strategy_ranking.html.slim
.title
  h2 戦略ランキング
br
br

.col-md-3
  = render partial: 'shared/sidemenu', locals: { lid: @league.id, active: { strategy_ranking: 'active' } }

.col-md-9
  table.table-base.datatable50
    thead
      tr
        th 順位
        th 戦略名
        th 提出日時
        th 得点
        th 最大ABCサイズ
        th ステート数
        th 関数の定義数
    tbody
      - @strategies.each.with_index(1) do |strategy, i|
        tr
          td.center= i
          td.center= strategy.player.snum
          td.center= format_time(strategy.created_at)
          td.right= format_score(strategy.score)
          td.right= format_score(strategy.abc_size)
          td.right= strategy.statement
          td.right= strategy.func_num