config/routes.rb
Wint::Application.routes.draw do
  ##================================================
  ##  Session
  ##================================================

  ##--  Session
  get  'login'          => 'sessions#new', as: :login
  post 'login'          => 'sessions#create'
  get  'logout'         => 'sessions#destroy', as: :logout
  get  'destroy_player' => 'sessions#destroy_player', as: :destroy_player

  ##================================================
  ##  Analysis
  ##================================================

  ##--  Analysis
  get 'analysis'                 => 'analysis#list', as: :analysis_list
  get 'analysis/:lid'            => 'analysis#league', as: :analysis_league
  get 'analysis/:lid/refresh'    => 'analysis#refresh', as: :analysis_refresh
  get 'analysis/:lid/strategies' => 'analysis#strategies', as: :analysis_strategies
  get 'analysis/:lid/player_ranking' => 'analysis#player_ranking', as: :analysis_player_ranking
  get 'analysis/:lid/strategy_ranking' => 'analysis#strategy_ranking', as: :analysis_strategy_ranking
  get 'analysis/:lid/code/:sid'  => 'analysis#code', as: :analysis_player_code
  get 'analysis/:lid/:pid'       => 'analysis#player', as: :analysis_player
  get 'analysis/:lid/:pid/:num'  => 'analysis#strategy', as: :analysis_strategy

  ##--  Download
  get 'downloads/:lid/best_strategies' => 'download#best_strategies', as: :download_best_strategies
  get 'downloads/:lid/all_strategies'  => 'download#all_strategies', as: :download_all_strategies
  get 'downloads/:lid/best_analysis'   => 'download#best_analysis', as: :download_best_analysis
  get 'downloads/:lid/all_analysis'    => 'download#all_analysis', as: :download_all_analysis

  ##================================================
  ##  Main
  ##================================================
  ##--  Main
  get   'main/select'                => 'mains#select', as: :main_select
  get   'main/set_player/:pid'       => 'mains#set_player', as: :main_set_player
  get   'main/ranking'               => 'mains#ranking', as: :main_ranking
  get   'main/mypage'                => 'mains#mypage', as: :main_mypage
  get   'main/mypage/strategy/:num'  => 'mains#strategy', as: :main_strategy
  get   'main/mypage/submit'         => 'submits#new', as: :submits_new
  post  'main/mypage/submit'         => 'submits#create'
  get   'main/edit_name'             => 'mains#edit_name', as: :main_edit_name
  patch 'main/edit_name'             => 'mains#update_name'
  get   'main/edit_password'         => 'mains#edit_password', as: :main_edit_password
  patch 'main/edit_password'         => 'mains#update_password'

  ##================================================
  ##  Admin
  ##================================================

  ##--  User
  get   'admin/users'                    => 'users#list', as: :users
  get   'admin/users/new'                => 'users#new', as: :users_new
  post  'admin/users/new'                => 'users#create'
  get   'admin/users/new_many'           => 'users#new_many', as: :users_new_many
  post  'admin/users/new_many'           => 'users#create_many'
  get   'admin/users/:uid/edit'          => 'users#edit', as: :users_edit
  patch 'admin/users/:uid/edit'          => 'users#update'
  get   'admin/users/:uid/edit_password' => 'users#edit_password', as: :users_edit_password
  patch 'admin/users/:uid/edit_password' => 'users#update_password', as: :users_update_password
  get   'admin/users/:uid/toggle'        => 'users#toggle', as: :users_toggle

  ##--  League
  get   'admin/leagues'                   => 'leagues#list', as: :leagues
  get   'admin/leagues/new'               => 'leagues#new', as: :leagues_new
  post  'admin/leagues/new'               => 'leagues#create'
  get   'admin/leagues/:lid/edit'         => 'leagues#edit', as: :leagues_edit
  patch 'admin/leagues/:lid/edit'         => 'leagues#update'
  get   'admin/leagues/:lid/toggle'       => 'leagues#toggle', as: :leagues_toggle
  get   'admin/leagues/:lid/toggle_analy' => 'leagues#toggle_analy', as: :leagues_toggle_analy

  ##--  Player
  get   'admin/players'             => 'players#list', as: :players
  get   'admin/players/select'      => 'players#select', as: :players_select
  get   'admin/players/new_many'    => 'players#new_many', as: :players_new_many
  post  'admin/players/new_many'    => 'players#create_many'
  get   'admin/players/new'         => 'players#new', as: :players_new
  post  'admin/players/new'         => 'players#create'
  get   'admin/players/:pid/edit'   => 'players#edit', as: :players_edit
  patch 'admin/players/:pid/edit'   => 'players#update'
  get   'admin/players/:pid/toggle' => 'players#toggle', as: :players_toggle
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  include GraphGenerator

  def ranking
    @league = League.includes(players: {best: :strategy}).find(session[:lid])
    @players = @league.players_ranking
  end

  def mypage
    @player = current_player
    @submits = @player.submits.includes(:strategy)
    @league = @player.league
    @line_score = line_score(@player.id)
  end

  def strategy
    player = current_player
    @strategy = player.submits.where(number: params[:num]).first.strategy
    @scatter_abc_size = scatter_abc_size(player.league_id, @strategy.id)
    @result_table = @strategy.get_result_table
  end

  def select
    @players = @current_user.players
  end

  def set_player
    player = Player.where(id: params[:pid]).first
    unless @current_user.id == player.user.id
      @current_user.update(is_active: false)
      redirect_to login_path, alert: "不正なアクセスを検出しました。" and return
    end
    session[:pid] = player.id
    session[:lid] = player.league.id
    redirect_to main_mypage_path and return
  end

  def edit_name
    @player = @current_player
  end

  def update_name
    @player = @current_player
    render :edit_name and return unless @player.update(player_params)
    render "shared/reload"
  end

  def edit_password
    @user = @current_user
  end

  def update_password
    @user = @current_user
    render :edit_password and return unless @user.update(user_params)
    render "shared/reload"
  end

  private

  def player_params
    params.require(:player).permit(:name)
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/mains/mypage.html.slim
.title
  .row
    .col-xs-5
      h2= @player.name
    .col-xs-7
      br
      - if @league.open?
        = link_to submits_new_path, data: {remote: true} do
          button.btn.btn-primary
            = fa_icon "folder-open", text: "戦略提出"
br
br

.row
  table.table-base.datatable-desc
    thead
      tr
        th 提出番号
        th 得点
        th 最大ABCサイズ
        th ステータス
        th 提出日時
        th 戦略コメント
    tbody
      - @submits.each do |submit|
        - if submit.exec_success?
          | <tr>
          - if @league.is_analy
            td.center= link_to "%03d" % submit.number, main_strategy_path(num: submit.number)
          - else
            td.center= "%03d" % submit.number
        - elsif submit.status == Submit::STATUS_RUNNING
          | <tr class="warning">
          td.center= "%03d" % submit.number
        - else
          | <tr class="danger">
          td.center= "%03d" % submit.number
        td.right= submit.strategy ? format_score(submit.strategy.score) : '???'
        td.right= submit.strategy ? format_score(submit.strategy.abc_size) : '???'
        td.center= Submit.status_options[submit.status]
        td.center= format_time(submit.created_at)
        td= submit.comment

.row
  = high_chart('line_score', @line_score)

app/views/mains/ranking.html.slim
.title
  h2 ランキング
br
br

ul.nav.nav-tabs
  li.active
    a href="#all" data-toggle="tab" 全体ランキング
  li
    a href="#rank" data-toggle="tab" 受講者ランキング
br

.tab-content
  .tab-pane.active#all
    table.table.table-base.datatable50
      thead
        tr
          th 順位
          th ランク
          th 得点
          th 最大ABCサイズ
          th プレイヤ名
          th 達成度
          th コメント
      tbody
        - @players.each.with_index(1) do |player, i|
          - klass = 'info' if @current_player.id == player.id
          tr class="#{klass}"
            td.center= i
            td.center= @league.rank(player.best.strategy)
            td.right= format_score(player.best.strategy.score)
            td.right= format_score(player.best.strategy.abc_size)
            td.center= player.name
            td.right= format_achievement(@league.achievement(player.best.strategy))
            td= player.best.comment
  .tab-pane#rank
    table.table.table-base.datatable50
      thead
        tr
          th 順位
          th ランク
          th 得点
          th 最大ABCサイズ
          th プレイヤ名
          th 達成度
          th コメント
      tbody
        - @players.select { |p| !p.auditor? }.each.with_index(1) do |player, i|
          - klass = 'info' if @current_player.id == player.id
          tr class="#{klass}"
            td.center= i
            td.center= @league.rank(player.best.strategy)
            td.right= format_score(player.best.strategy.score)
            td.right= format_score(player.best.strategy.abc_size)
            td.center= player.name
            td.right= format_achievement(@league.achievement(player.best.strategy))
            td= player.best.comment

app/views/mains/select.html.slim
.title
  h2 プレイヤ選択
br
br

.main.select

  table.table-base
    thead
      tr
        th.player プレイヤ名
        th.league リーグ名
        th.score 理想得点
        th.open 開催期間
    tbody
      - @players.each do |player|
        - league = player.league
        tr
          td.player= link_to player.name, main_set_player_path(pid: player.id)
          td.league= league.name
          td.score= league.limit_score
          td.open
            = format_time(league.start_at)
            | &nbsp;～&nbsp;
            = format_time(league.end_at)

app/views/mains/strategy.html.slim
.title
  .row
    .col-xs-5
      h2 戦略詳細
    .col-xs-7
br
br

.row
  .col-lg-6
    table.table-base
      thead
        tr
          - @result_table.shift.each do |head|
            th= head
      tbody
        - @result_table.each do |line|
          tr
            td.name style="font-weight: bold;" = line.shift
            - line.each do |elem|
              td.num= elem
  .col-lg-6
    = high_chart("scatter_abc_size", @scatter_abc_size)

br
.row
  .col-lg-5
    textarea.form-control disabled='disabled' style='height: 600px'
      = File.read(@strategy.submit.src_file)
  .col-lg-7
    table.table.table-base.datatable
      thead
        tr
          th 行番号
          th 関数名
          th ABCサイズ
          th 代入回数
          th 関数の呼出回数
          th 条件文の数
      tbody
        - @strategy.adlint_analysis.functions.values.each do |function|
          - abc_size = function.abc_size
          - klass = 'warning' if abc_size > 20
          - klass = 'danger' if abc_size > 30
          tr class="#{klass}"
            td.center= function.position
            td.center= function.name
            td.right= format_score(abc_size)
            td.right= function.assignment.count
            td.right= function.branch
            td.right= function.condition