config/routes.rb
Wint::Application.routes.draw do
  ##================================================
  ##  Session
  ##================================================

  ##--  Session
  get  'login'          => 'sessions#new', as: :login
  post 'login'          => 'sessions#create'
  get  'logout'         => 'sessions#destroy', as: :logout
  get  'destroy_player' => 'sessions#destroy_player', as: :destroy_player

  ##================================================
  ##  Analysis
  ##================================================

  ##--  Analysis
  get 'analysis'                 => 'analysis#list', as: :analysis_list
  get 'analysis/:lid'            => 'analysis#league', as: :analysis_league
  get 'analysis/:lid/refresh'    => 'analysis#refresh', as: :analysis_refresh
  get 'analysis/:lid/strategies' => 'analysis#strategies', as: :analysis_strategies
  get 'analysis/:lid/player_ranking' => 'analysis#player_ranking', as: :analysis_player_ranking
  get 'analysis/:lid/strategy_ranking' => 'analysis#strategy_ranking', as: :analysis_strategy_ranking
  get 'analysis/:lid/code/:sid'  => 'analysis#code', as: :analysis_player_code
  get 'analysis/:lid/:pid'       => 'analysis#player', as: :analysis_player
  get 'analysis/:lid/:pid/:num'  => 'analysis#strategy', as: :analysis_strategy

  ##--  Download
  get 'downloads/:lid/best_strategies' => 'download#best_strategies', as: :download_best_strategies
  get 'downloads/:lid/all_strategies'  => 'download#all_strategies', as: :download_all_strategies
  get 'downloads/:lid/best_analysis'   => 'download#best_analysis', as: :download_best_analysis
  get 'downloads/:lid/all_analysis'    => 'download#all_analysis', as: :download_all_analysis

  ##================================================
  ##  Main
  ##================================================
  ##--  Main
  get   'main/select'                => 'mains#select', as: :main_select
  get   'main/set_player/:pid'       => 'mains#set_player', as: :main_set_player
  get   'main/ranking'               => 'mains#ranking', as: :main_ranking
  get   'main/mypage'                => 'mains#mypage', as: :main_mypage
  get   'main/mypage/strategy/:num'  => 'mains#strategy', as: :main_strategy
  get   'main/mypage/submit'         => 'submits#new', as: :submits_new
  post  'main/mypage/submit'         => 'submits#create'
  get   'main/edit_name'             => 'mains#edit_name', as: :main_edit_name
  patch 'main/edit_name'             => 'mains#update_name'
  get   'main/edit_password'         => 'mains#edit_password', as: :main_edit_password
  patch 'main/edit_password'         => 'mains#update_password'

  ##================================================
  ##  Admin
  ##================================================

  ##--  User
  get   'admin/users'                    => 'users#list', as: :users
  get   'admin/users/new'                => 'users#new', as: :users_new
  post  'admin/users/new'                => 'users#create'
  get   'admin/users/new_many'           => 'users#new_many', as: :users_new_many
  post  'admin/users/new_many'           => 'users#create_many'
  get   'admin/users/:uid/edit'          => 'users#edit', as: :users_edit
  patch 'admin/users/:uid/edit'          => 'users#update'
  get   'admin/users/:uid/edit_password' => 'users#edit_password', as: :users_edit_password
  patch 'admin/users/:uid/edit_password' => 'users#update_password', as: :users_update_password
  get   'admin/users/:uid/toggle'        => 'users#toggle', as: :users_toggle

  ##--  League
  get   'admin/leagues'                   => 'leagues#list', as: :leagues
  get   'admin/leagues/new'               => 'leagues#new', as: :leagues_new
  post  'admin/leagues/new'               => 'leagues#create'
  get   'admin/leagues/:lid/edit'         => 'leagues#edit', as: :leagues_edit
  patch 'admin/leagues/:lid/edit'         => 'leagues#update'
  get   'admin/leagues/:lid/toggle'       => 'leagues#toggle', as: :leagues_toggle
  get   'admin/leagues/:lid/toggle_analy' => 'leagues#toggle_analy', as: :leagues_toggle_analy

  ##--  Player
  get   'admin/players'             => 'players#list', as: :players
  get   'admin/players/select'      => 'players#select', as: :players_select
  get   'admin/players/new_many'    => 'players#new_many', as: :players_new_many
  post  'admin/players/new_many'    => 'players#create_many'
  get   'admin/players/new'         => 'players#new', as: :players_new
  post  'admin/players/new'         => 'players#create'
  get   'admin/players/:pid/edit'   => 'players#edit', as: :players_edit
  patch 'admin/players/:pid/edit'   => 'players#update'
  get   'admin/players/:pid/toggle' => 'players#toggle', as: :players_toggle
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  league_id  :integer          not null
#  name       :string(255)      not null
#  role       :integer          default(0), not null
#  submit_id  :integer          not null
#  is_active  :boolean          default(TRUE), not null
#  created_at :datetime
#  updated_at :datetime
#  data_dir   :string(255)      not null
#

class Player < ActiveRecord::Base
  belongs_to :user
  belongs_to :league
  belongs_to :best, class_name: :Submit, foreign_key: :submit_id
  has_many :submits, dependent: :delete_all
  has_many :strategies, through: :submits

  validates :name, presence: true, length: { maximum: 10 }

  Scope.active(self)

  ROLE_PARTICIPANT = 0
  ROLE_AUDITOR = 1

  after_create :after_create

  def after_create
    path = format("#{league.data_dir}/%04d", id)
    Dir.mkdir(path)
    update(data_dir: path)
  end

  def snum
    format("#{user.snum}_%03d", best.strategy.number)
  end

  def auditor?
    role == ROLE_AUDITOR
  end

  def self.role_options
    {
      ROLE_PARTICIPANT => '受講者',
      ROLE_AUDITOR => '聴講者'
    }
  end

  public_class_method

  def self.create(attributes)
    attributes[:data_dir] ||= 'dummy'
    attributes[:submit_id] ||= 0
    super(attributes)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def list
    @players = Player.all
  end

  def select
    @users = User.all
  end

  def new_many
    user_ids = []
    user_ids = params.require(:user_id).keys if params[:user_id].present?
    @users = User.where(id: user_ids)
    @league = League.where(id: params[:league_id]).first
  end

  def create_many
    params.require(:player).each do |user_id, value|
      Player.create(league_id: params[:league_id], user_id: user_id,
                    name: value[:name], role: value[:role])
    end
    redirect_to players_path
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    render :new && return unless @player.save
    redirect_to players_path
  end

  def edit
    @player = Player.find(params[:pid])
  end

  def update
    @player = Player.find(params[:pid])
    render :edit && return unless @player.update(player_params)
    render 'shared/reload'
  end

  def toggle
    @player = Player.find(params[:pid])
    @player.update(is_active: !@player.is_active)
    redirect_to players_path
  end

  private

  def player_params
    params.require(:player).permit(:user_id, :league_id, :name, :role)
  end
end

app/views/players/list.html.slim
.title
  .row
    .col-xs-5
      h2 プレイヤ一覧
    .col-xs-7
      br
      = link_to players_select_path do
        button.btn.btn-primary
          = fa_icon "share", text: "ユーザ選択画面へ"
br
br

.players.list

  table.table.table-base.datatable
    thead
      tr
        th.name プレイヤ名
        th.role ロール
        th.user ユーザ名
        th.league リーグ名
        th.edit 編集
        th.toggle 有効 / 無効
    tbody
      - @players.each do |player|
        = render partial: "shared/row", locals: {is_active: player.is_active}
        td.name= player.name
        td.role= Player.role_options[player.role]
        td.user= player.user.name
        td.league= player.league.name
        td.edit= link_to players_edit_path(pid: player.id), remote: true do
          = render partial: "shared/buttons/edit"
        td.toggle= link_to players_toggle_path(pid: player.id) do
          = render partial: "shared/buttons/toggle", locals: {is_active: player.is_active}

app/views/players/new_many.html.slim
= form_tag players_new_many_path do
  = hidden_field_tag :league_id, @league.id
  .title
    .row
      .col-lg-5
        h2
          | プレイヤ一括登録
          small
            | &nbsp;&nbsp;
            = @league.name
      .col-lg-7
        br
        button.btn.btn-primary
          = fa_icon "tags", text: "プレイヤ一括登録"
  br
  br

  .players.new_many.row
    table.table-base
      thead
        tr
          th.name プレイヤ名
          th.role ロール
          th.snum 学籍番号
          th.user ユーザ名
          th.category 区分
      tbody
        - @users.each do |user|
          tr
            td.name= text_field "player[#{user.id}]", :name, value: user.name
            td.name= select "player[#{user.id}]", :role, Player.role_options.invert
            td.snum= user.snum
            td.user= user.name
            td.category= User.category_options[user.category]

app/views/players/select.html.slim
= form_tag players_new_many_path, method: :get do
  .title
    .row
      .col-lg-5
        h2 ユーザ選択
      .col-lg-7
        br
        button.btn.btn-primary
          = fa_icon "share", text: "プレイヤ登録画面へ"
  br
  br

  .players.select
    .row
      .col-sm-4
      .col-sm-4
        table.table-base
          tr
            th リーグ
            td= select_tag :league_id, options_for_select(League.select_format)
  
    table.table-base.datatable
      thead
        tr
          th.check
          th.snum 学籍番号
          th.category 区分
          th.name 氏名
      tbody
        - @users.each do |user|
          tr
            td.check= check_box_tag "user_id[#{user.id}]"
            td.snum= user.snum
            td.category= User.category_options[user.category]
            td.name= user.name